SENDGRID_API_KEY: ""
GOOGLE_MAPS_API_KEY: ""
TOKEN_LIFESPAN: 2592000
ACCOUNT_CONFIRMATION_URL: "http://cruise.eastus.cloudapp.azure.com:8080/#/confirm-account/"
RESET_PASSWORD_URL: "http://cruise.eastus.cloudapp.azure.com:8080/#/new-password/"
INVITATION_URL: "http://cruise.eastus.cloudapp.azure.com:8080/#/log-in"
EMAIL: "cruiseteam2siit@gmail.com"
EMAIL_SUBJECT: "Welcome to Cruise"
DRIVER_ARRIVED_SUBJECT: "Cruise - The driver has arrived at the pickup location"
RIDE_REMINDER: "Cruise - ride reminder"
RIDE_REJECTED: "Cruise - your scheduled ride was rejected"
RESET_PASSWORD_EMAIL_SUBJECT: "Cruise - Reset password"
PYTHON_SERVER_IP: "https://a3cvd3.deta.dev"
